extends Node

class_name Items
const maximum = 9999
var content:Dictionary = {
	1: {
		"caption": tr("log.caption"),
		"description": tr("log.description"),
		"type": "building_materials.type",
		"purchase": 1,
		"sale": 0,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/resources/log.png"),
	},
	2: {
		"caption": tr("plank.caption"),
		"description": tr("plank.description"),
		"type": "building_materials.type",
		"purchase": 1,
		"sale": 0,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/resources/plank.png"),
	},
	3: {
		"caption": tr("stone.caption"),
		"description": tr("stone.description"),
		"type": "building_materials.type",
		"purchase": 1,
		"sale": 0,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/resources/stone.png"),
	},
	4: {
		"caption": tr("cobblestone.caption"),
		"description": tr("cobblestone.description"),
		"type": "building_materials.type",
		"purchase": 1,
		"sale": 0,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/resources/cobblestone.png"),
	},
	5: {
		"caption": tr("coal.caption"),
		"description": tr("coal.description"),
		"type": "building_materials.type",
		"purchase": 1,
		"sale": 0,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/resources/coal.png"),
	},
	6: {
		"caption": tr("copper_ore.caption"),
		"description": tr("copper_ore.description"),
		"type": "ore.type",
		"purchase": 1,
		"sale": 0,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/resources/copper_ore.png"),
	},
	7: {
		"caption": tr("iron_ore.caption"),
		"description": tr("iron_ore.description"),
		"type": "ore.type",
		"purchase": 1,
		"sale": 0,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/resources/iron_ore.png"),
	},
	8: {
		"caption": tr("bauxite_ore.caption"),
		"description": tr("bauxite_ore.description"),
		"type": "ore.type",
		"purchase": 1,
		"sale": 0,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/resources/bauxite_ore.png"),
	},
	9: {
		"caption": tr("copper_ingot.caption"),
		"description": tr("copper_ingot.description"),
		"type": "building_materials.type",
		"purchase": 1,
		"sale": 0,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/resources/copper_ingot.png"),
	},
	10: {
		"caption": tr("iron_ingot.caption"),
		"description": tr("iron_ingot.description"),
		"type": "building_materials.type",
		"purchase": 1,
		"sale": 0,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/resources/iron_ingot.png"),
	},
	11: {
		"caption": tr("aluminum_ingot.caption"),
		"description": tr("aluminum_ingot.description"),
		"type": "building_materials.type",
		"purchase": 1,
		"sale": 0,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/resources/aluminum_ingot.png"),
	},
	12: {
		"caption": tr("carrot_packet.caption"),
		"description": tr("carrot_packet.description"), # Маленькие семена для выращивания моркови. Посадите их на плодородной земле, поливайте и ждите урожая.
		"specifications": {
			"growth": tr("carrot.growth"),
			"productivity": tr("carrot.productivity"),
			"conditions": tr("carrot.conditions"),
		},
		"type": "seeds",
		"purchase": 1,
		"sale": 0,
		"crop": 1,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/seeds packets/packet_1.png"),
	},
	13: {
		"caption": tr("potato_packet.caption"),
		"description": tr("potato_packet.description"), # Эти семена помогут вырастить питательный картофель. Посадите их в землю, поливайте и наблюдайте за ростом.
		"specifications": {
			"growth": tr("potato.growth"),
			"productivity": tr("potato.productivity"),
			"conditions": tr("potato.conditions"),
		},
		"type": "seeds",
		"purchase": 1,
		"sale": 0,
		"crop": 2,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/seeds packets/packet_2.png"),
	},
	14: {
		"caption": tr("radish_packet.caption"),
		"description": tr("radish_packet.description"), # Маленькие семена для быстрого выращивания хрустящего редиса. Посадите их, поливайте и ждите урожая.
		"specifications": {
			"growth": tr("radish.growth"),
			"productivity": tr("radish.productivity"),
			"conditions": tr("radish.conditions"),
		},
		"type": "seeds",
		"purchase": 1,
		"sale": 0,
		"crop": 3,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/seeds packets/packet_3.png"),
	},
	15: {
		"caption": tr("cabbage_packet.caption"),
		"description": tr("radish_packet.description"), # Семена для выращивания плотной и сочной капусты. Посадите их в землю, поливайте и ждите зрелости.
		"specifications": {
			"growth": tr("cabbage.growth"),
			"productivity": tr("cabbage.productivity"),
			"conditions": tr("cabbage.conditions"),
		},
		"type": "seeds",
		"purchase": 1,
		"sale": 0,
		"crop": 4,
		"icon": load("res://assets/resources/ui/interactive/inventory/items/seeds packets/packet_4.png"),
	},
}
