extends Node2D

class_name Crops
var crops:Dictionary = {
	"atlas": load("res://assets/resources/farming/crops.png"),
	"width": 16,
	"height": 32,
	"check_watering": 5,
	1: {
		"caption" = tr("carrot.caption"),
		"type" = "vegetable", 
		"season" = "spring",
		"growth_rate" = 25,
		"growth_level" = 5,
		"mortality" = 5,
		"productivity" = [5,10],
		"X" = 0, "Y" = 0,
		"crop_id" = 1,
	},
	2: {
		"caption" = tr("potato.caption"),
		"type" = "vegetable", 
		"season" = "spring",
		"growth_rate" = 50,
		"growth_level" = 6, 
		"mortality" = 5,
		"productivity" = [5,10], 
		"X" = 0, "Y" = 32,
		"crop_id" = 1,
	},
	3: {
		"caption" = tr("radish.caption"),
		"type" = "vegetable", 
		"season" = "spring",
		"growth_rate" = 35,
		"growth_level" = 4, 
		"mortality" = 5,
		"productivity" = [5,10], 
		"X" = 0, "Y" = 64,
		"crop_id" = 1,
	},
	4: {
		"caption" = tr("cabbage.caption"),
		"type" = "vegetable", 
		"season" = "spring",
		"growth_rate" = 75,
		"growth_level" = 4, 
		"mortality" = 5,
		"productivity" = [5,10], 
		"X" = 0, "Y" = 96,
		"crop_id" = 1,
	},
}
